# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17 for SonarCloud Analysis
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Upgraded from '11' to meet SonarCloud runner requirements
        distribution: 'temurin'
        cache: maven
        
    - name: Build, test, and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }} # Note: Sonar generally expects GITHUB_TOKEN for PR decoration
      run: mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=mkpel -Dsonar.projectKey=mkpel_coba-kode-inspection
